baseURL = "https://learnmetapost.onrender.com/"
languageCode = "en-us"
title = "Learn MetaPost"
theme = "hugo-theme-techdoc"
googleAnalytics = "G-20EGJCEC1L"

[params]

menu_style = "open-menu"
menu_exclusion = ["archives"]

[params.copyright]
prefix = ""
holder = "Johan Sivertsen"
startYear = "2015"
suffix = ""
